version: '3'

services:
  # task-hub-front:
  #   build:
  #     context: ./task-hub-front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"

  api:
    build:
      context: ./api
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb_user
      MYSQL_PASSWORD: mydb_password
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      # - task-hub-front
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html

volumes:
  mysql-data:
